couchbase:
    image: couchbase/server:latest
    ports:
        - "8091:8091"
        - "8092:8092"
        - "11210:11210"
    restart: always

zookeeper:
    image: wurstmeister/zookeeper
    ports:
        - "2181:2181"
    restart: always

kafka:
    image: cantireinnovations/kafka:kafka-v0.8.2.1_scala-v2.10
    ports:
        - "9092:9092"
    links:
        - zookeeper:zk
    environment:
        - DEV=true
        - KAFKA_ADVERTISED_HOST_NAME=localhost
        - KAFKA_ADVERTISED_PORT=9092
        - KAFKA_BROKER_ID=1
    restart: always
