couchbase:
    image: couchbase/server:latest
    ports:
        - "8091:8091"
        - "8092:8092"
        - "11210:11210"
    restart: always

zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181:2181"
  restart: always

kafka:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 172.17.42.1
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  restart: always
